baseURL = 'https://ham.abhashtech.com/'
languageCode = 'en-us'
title = 'ASOC Exam Notes'
theme = 'hugo-theme-relearn'
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
