baseURL = 'https://ham.abhashtech.com/'
languageCode = 'en-us'
title = 'Prepration for ASOC Exam'
theme = 'hugo-theme-relearn'
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
